# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Mainwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys

from PyQt5.QtWidgets import *

from Mainwin import Ui_Form

"""
class Ui_Form(object):
    def __init__(self):
        self.inputtext = None
        self.outputLabel = None
        self.graphLabel = None
        self.tipsLabel = None
        self.pushButton = None

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 700)
        Form.setMinimumSize(QtCore.QSize(700, 700))
        Form.setMaximumSize(QtCore.QSize(700, 700))
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(450, 270, 99, 28))
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.tipsLabel = QtWidgets.QLabel(Form)
        self.tipsLabel.setGeometry(QtCore.QRect(350, 30, 291, 191))
        self.tipsLabel.setStyleSheet("font: 75 9pt \"微软雅黑\";")
        self.tipsLabel.setObjectName("tipsLabel")
        self.graphLabel = QtWidgets.QLabel(Form)
        self.graphLabel.setGeometry(QtCore.QRect(30, 360, 300, 300))
        self.graphLabel.setText("")
        self.graphLabel.setObjectName("graphLabel")
        self.outputLabel = QtWidgets.QLabel(Form)
        self.outputLabel.setGeometry(QtCore.QRect(350, 360, 300, 300))
        self.outputLabel.setText("")
        self.outputLabel.setObjectName("outputLabel")
        self.inputtext = QtWidgets.QTextEdit(Form)
        self.inputtext.setGeometry(QtCore.QRect(30, 30, 300, 300))
        self.inputtext.setObjectName("inputtext")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.inputtext, self.pushButton)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "isEulerGraph"))
        self.pushButton.setText(_translate("Form", "是欧拉图吗？"))
        self.tipsLabel.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\"\n"
                                                  "font-size:12pt;\">请在左边的文本框中按行输入</span></p><p "
                                                  "align=\"center\"><span\n"
                                                  "style=\" font-size:12pt;\">一个表示图的邻接矩阵</span></p><p "
                                                  "align=\"center\"><span\n"
                                                  "style=\" font-size:12pt;\">格式参考文本框内示例</span></p></body></html>\n"
                                                  "                "))

"""
if __name__ == '__main__':
    app = QApplication(sys.argv)
    mainWin = QWidget()
    ui = Ui_Form()
    ui.setupUi(mainWin)
    mainWin.show()
    sys.exit(app.exec_())
